// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: api/v1alpha1/shogi.proto

package v1alpha1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PositionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      string                 `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionRequest) Reset() {
	*x = PositionRequest{}
	mi := &file_api_v1alpha1_shogi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionRequest) ProtoMessage() {}

func (x *PositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_shogi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionRequest.ProtoReflect.Descriptor instead.
func (*PositionRequest) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_shogi_proto_rawDescGZIP(), []int{0}
}

func (x *PositionRequest) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

type ThinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Btime         int32                  `protobuf:"varint,1,opt,name=btime,proto3" json:"btime,omitempty"`
	Wtime         int32                  `protobuf:"varint,2,opt,name=wtime,proto3" json:"wtime,omitempty"`
	Byoyomi       int32                  `protobuf:"varint,3,opt,name=byoyomi,proto3" json:"byoyomi,omitempty"`
	Nodes         int32                  `protobuf:"varint,4,opt,name=nodes,proto3" json:"nodes,omitempty"`
	Mate          int32                  `protobuf:"varint,5,opt,name=mate,proto3" json:"mate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThinkRequest) Reset() {
	*x = ThinkRequest{}
	mi := &file_api_v1alpha1_shogi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThinkRequest) ProtoMessage() {}

func (x *ThinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_shogi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThinkRequest.ProtoReflect.Descriptor instead.
func (*ThinkRequest) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_shogi_proto_rawDescGZIP(), []int{1}
}

func (x *ThinkRequest) GetBtime() int32 {
	if x != nil {
		return x.Btime
	}
	return 0
}

func (x *ThinkRequest) GetWtime() int32 {
	if x != nil {
		return x.Wtime
	}
	return 0
}

func (x *ThinkRequest) GetByoyomi() int32 {
	if x != nil {
		return x.Byoyomi
	}
	return 0
}

func (x *ThinkRequest) GetNodes() int32 {
	if x != nil {
		return x.Nodes
	}
	return 0
}

func (x *ThinkRequest) GetMate() int32 {
	if x != nil {
		return x.Mate
	}
	return 0
}

type BestMove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bestmove      string                 `protobuf:"bytes,1,opt,name=bestmove,proto3" json:"bestmove,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BestMove) Reset() {
	*x = BestMove{}
	mi := &file_api_v1alpha1_shogi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BestMove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BestMove) ProtoMessage() {}

func (x *BestMove) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1alpha1_shogi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BestMove.ProtoReflect.Descriptor instead.
func (*BestMove) Descriptor() ([]byte, []int) {
	return file_api_v1alpha1_shogi_proto_rawDescGZIP(), []int{2}
}

func (x *BestMove) GetBestmove() string {
	if x != nil {
		return x.Bestmove
	}
	return ""
}

var File_api_v1alpha1_shogi_proto protoreflect.FileDescriptor

const file_api_v1alpha1_shogi_proto_rawDesc = "" +
	"\n" +
	"\x18api/v1alpha1/shogi.proto\x12\fapi.v1alpha1\x1a\x1bgoogle/protobuf/empty.proto\"-\n" +
	"\x0fPositionRequest\x12\x1a\n" +
	"\bposition\x18\x01 \x01(\tR\bposition\"~\n" +
	"\fThinkRequest\x12\x14\n" +
	"\x05btime\x18\x01 \x01(\x05R\x05btime\x12\x14\n" +
	"\x05wtime\x18\x02 \x01(\x05R\x05wtime\x12\x18\n" +
	"\abyoyomi\x18\x03 \x01(\x05R\abyoyomi\x12\x14\n" +
	"\x05nodes\x18\x04 \x01(\x05R\x05nodes\x12\x12\n" +
	"\x04mate\x18\x05 \x01(\x05R\x04mate\"&\n" +
	"\bBestMove\x12\x1a\n" +
	"\bbestmove\x18\x01 \x01(\tR\bbestmove2\x8e\x01\n" +
	"\fShogiService\x12A\n" +
	"\bPosition\x12\x1d.api.v1alpha1.PositionRequest\x1a\x16.google.protobuf.Empty\x12;\n" +
	"\x05Think\x12\x1a.api.v1alpha1.ThinkRequest\x1a\x16.api.v1alpha1.BestMoveB:Z8github.com/nokamoto/shogithink/pkg/api/v1alpha1;v1alpha1b\x06proto3"

var (
	file_api_v1alpha1_shogi_proto_rawDescOnce sync.Once
	file_api_v1alpha1_shogi_proto_rawDescData []byte
)

func file_api_v1alpha1_shogi_proto_rawDescGZIP() []byte {
	file_api_v1alpha1_shogi_proto_rawDescOnce.Do(func() {
		file_api_v1alpha1_shogi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1alpha1_shogi_proto_rawDesc), len(file_api_v1alpha1_shogi_proto_rawDesc)))
	})
	return file_api_v1alpha1_shogi_proto_rawDescData
}

var file_api_v1alpha1_shogi_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_v1alpha1_shogi_proto_goTypes = []any{
	(*PositionRequest)(nil), // 0: api.v1alpha1.PositionRequest
	(*ThinkRequest)(nil),    // 1: api.v1alpha1.ThinkRequest
	(*BestMove)(nil),        // 2: api.v1alpha1.BestMove
	(*emptypb.Empty)(nil),   // 3: google.protobuf.Empty
}
var file_api_v1alpha1_shogi_proto_depIdxs = []int32{
	0, // 0: api.v1alpha1.ShogiService.Position:input_type -> api.v1alpha1.PositionRequest
	1, // 1: api.v1alpha1.ShogiService.Think:input_type -> api.v1alpha1.ThinkRequest
	3, // 2: api.v1alpha1.ShogiService.Position:output_type -> google.protobuf.Empty
	2, // 3: api.v1alpha1.ShogiService.Think:output_type -> api.v1alpha1.BestMove
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_v1alpha1_shogi_proto_init() }
func file_api_v1alpha1_shogi_proto_init() {
	if File_api_v1alpha1_shogi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1alpha1_shogi_proto_rawDesc), len(file_api_v1alpha1_shogi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1alpha1_shogi_proto_goTypes,
		DependencyIndexes: file_api_v1alpha1_shogi_proto_depIdxs,
		MessageInfos:      file_api_v1alpha1_shogi_proto_msgTypes,
	}.Build()
	File_api_v1alpha1_shogi_proto = out.File
	file_api_v1alpha1_shogi_proto_goTypes = nil
	file_api_v1alpha1_shogi_proto_depIdxs = nil
}
