name: Run Mage Tasks
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  mage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: go install github.com/magefile/mage@latest
      - run: mage -v
      - run: git diff --exit-code
