name: Lint Markdown
on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.md'
  push:
    branches:
      - main
    paths:
      - '**/*.md'
jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v20.0.0
        with:
          fix: true
          globs: '**/*.md'
